#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withtermcap,v 1.3 2014/10/25 17:37:21 ayoung Exp $
#   Basic configuration enabled using termcap
#

./configure_new \
	--with-8bit \
	--with-termlib=termcap \
	--with-dlmalloc \
	$*

