#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withncursesw,v 1.5 2024/05/28 12:39:07 cvsuser Exp $
#   Basic configuration enabled using ncursesw
#

./configure \
	--with-8bit \
	--with-mouse \
	--with-termlib=ncursesw \
	--with-dlmalloc \
	$*
