#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withmost,v 1.8 2024/05/28 12:39:07 cvsuser Exp $
#       auto select the terminal interface (ncurses, tinfo, curse, termcap and termlib)
#       enable most other third-party library support
#

./configure \
	--with-8bit		\
	--with-icu		\
	--with-apriconv		\
	--with-iconv		\
	--with-enca		\
	--with-dlmalloc		\
	$*
