#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withncurses,v 1.5 2024/05/28 12:39:07 cvsuser Exp $
#   Basic configuration enabled using ncurses
#

./configure \
	--with-8bit \
	--with-mouse \
	--with-termlib=ncurses \
	--with-dlmalloc \
	--with-contrib \
	$*
