#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withtermcap,v 1.4 2024/05/28 12:39:07 cvsuser Exp $
#   Basic configuration enabled using termcap
#

./configure \
	--with-8bit \
	--with-termlib=termcap \
	--with-dlmalloc \
	$*
