#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withtermlib,v 1.4 2024/05/28 12:39:07 cvsuser Exp $
#   Basic configuration enabled using interval termlib
#

./configure \
	--with-8bit \
	--with-termlib=termlib \
	--with-dlmalloc \
	$*
