#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withcurses,v 1.3 2024/05/28 12:39:07 cvsuser Exp $
#   Basic configuration enabled using curses
#

./configure \
	--with-8bit \
	--with-termlib=curses \
	--with-dlmalloc \
	$*
