#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withtinfo,v 1.4 2024/05/28 12:39:07 cvsuser Exp $
#   Basic configuration enabled using ncurses tinfo interface
#

./configure \
	--with-8bit \
	--with-termlib=tinfo \
	--with-dlmalloc \
	$*
