#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withcurses,v 1.2 2011/11/03 23:41:10 cvsuser Exp $
#   Basic configuration enabled using curses
#

./configure_new \
	--with-8bit \
	--with-termlib=curses \
	--with-dlmalloc \
	$*

