@echo off
echo Open Watcom 1.9 Build Environment
SET  OWC19=d:\tools\WC19
if NOT "%1" == "" SET OWC19=%1
SET PATH=%OWC19%\BINW;%PATH%
SET PATH=%OWC19%\BINNT;%PATH%
SET INCLUDE=%OWC19%\H\NT;%INCLUDE%
SET INCLUDE=%OWC19%\H\NT;%INCLUDE%
SET INCLUDE=%INCLUDE%;%OWC19%\H\NT\DIRECTX
SET INCLUDE=%INCLUDE%;%OWC19%\H\NT\DDK
SET INCLUDE=%OWC19%\H;%INCLUDE%
SET WATCOM=%OWC19%
SET EDPATH=%OWC19%\EDDAT
SET WHTMLHELP=%OWC19%\BINNT\HELP
SET WIPFC=%OWC19%\WIPFC
