# See: https://cirrus-ci.org/guide/quick-start/
# 
env:
  MAKE: gmake
  CIRRUS_CLONE_DEPTH: 3
  WITH_FEATURES:

freebsd_task:
  name: FreeBSD
  matrix:
    - name: FreeBSD 14.1
      freebsd_instance:
        image_family: freebsd-14-1
  timeout_in: 20m
  install_script:
    - pkg install -y bash gmake perl5 autoconf automake libtool pkgconf
    - pkg install -y flex bison wget asciidoc
    - pkg install -y gettext libiconv libarchive curl ncurses expat liblz4 lzo2 zstd
#   - /usr/local/bin/curl-config --configure
#   - /usr/local/bin/curl-config --cflags
    - find /usr -mount -name '*ncurses.h*' 2>/dev/null
  build_script:
    - NPROC=$(getconf _NPROCESSORS_ONLN)
    - ./configure ${WITH_FEATURES}
    - more acdefines.h
    - gmake release
  clean_script:
    - gmake release clean
