#!/usr/bin/perl -w
# -*- mode: perl; -*-
# $Id: buildinfo.pl,v 1.1 2020/06/03 21:57:23 cvsuser Exp $
# grief buildinfo generation
#
# Copyright Adam Young 2018-2020
#

use strict;
use warnings 'all';
use Getopt::Long;
use POSIX qw(strftime);

my $output  = "buildinfo.h";
my $package = undef;
my $name    = undef;
my $version = "0.0.1";
my $date    = undef;
my $build   = "1";
my $o_bindir = undef;
my $o_sbindir = undef;
my $o_libdir = undef;
my $o_libexecdir = undef;
my $o_datadir = undef;

my $help    = 0;

Usage() if (0 == GetOptions(
		'output=s'	=> \$output,
		'package=s'	=> \$package,
		'name=s'	=> \$name,
		'version=s'	=> \$version,
		'date=i'	=> \$date,
		'build=i'	=> \$build,
		'bindir:s'	=> \$o_bindir,
		'sbindir:s'	=> \$o_sbindir,
		'libdir:s'	=> \$o_libdir,
		'libexecdir:s'	=> \$o_libexecdir,
		'datadir:s'	=> \$o_datadir,
		'help'		=> \$help)
			|| $help);

$package = "Grief" if (! $package);
$name    = "Grief Edit" if (! $name);
$version = "0.0.1" if (! $version);
$date    = strftime('%Y%m%d', localtime) if (! $date);

Generate();

sub
Generate	#()
{
	open(FILE, ">${output}") or
		die "cannot create <${output}> : $!\n";

	my ($version1, $version2, $version3) =
		split(/\./, $version);

	$version2 = 0 if (! $version2);
	$version3 = 0 if (! $version3);

	print FILE <<"EOT";
// Auto-generated by Makefile
#define GR_PACKAGE "${package}"
#define GR_PACKAGE_NAME "${name}"
#define GR_VERSION "${version}"
#define GR_VERSION_1 ${version1}
#define GR_VERSION_2 ${version2}
#define GR_VERSION_3 ${version3}
#define GR_BUILD_DATE "${date}"
#define GR_BUILD_NUMBER "${build}"
EOT

	print FILE "#define GR_BUILD_BINDIR \"${o_bindir}\"\n"
		if ($o_bindir);

	print FILE "#define GR_BUILD_SBINDIR \"${o_sbindir}\"\n"
		if ($o_sbindir);

	print FILE "#define GR_BUILD_LIBDIR \"${o_libdir}\"\n"
		if ($o_libdir);

	print FILE "#define GR_BUILD_LIBEXECDIR \"${o_libexecdir}\"\n"
		if ($o_libexecdir);

	print FILE "#define GR_BUILD_DATADIR \"${o_datadir}\"\n"
		if ($o_datadir);

	close(FILE);
}


sub
Usage		# ([message])
{
	print "\nbuildinfo.h @_\n\n" if (@_);
	print <<EOU;

Usage: perl buildinfo.pl [options]

Options:
    --output <file>         Output file.
    --package <package>     Package label.
    --name <name>           Package name.
    --version <version>     Package version.
    --date <date>           Build date.
    --build <number>        Build number.

    --bindir <path>         bindir path.
    --sbindir <path>        sbindir path.
    --libdir <path>         libdir path.
    --libexecdir<path>      libexecdir path.
    --datadir <path>        datadir path.

    --help                  Help.

EOU
	exit 3;
}

1;

#end


