#!/bin/sh
# -*- mode: sh; -*-
# $Id: configure_build,v 1.7 2024/05/03 14:35:17 cvsuser Exp $
#

if [ ! -f "install-sh" ]; then
	cp auto/install-sh .
fi
if [ ! -f "config.guess" ]; then
	cp auto/config.guess .
fi
if [ ! -f "config.sub" ]; then
	cp auto/config.sub .
fi
if [ ! -f "missing" ]; then
	if [ -f "auto/missing" ]; then # optional
		cp auto/missing .
	fi
fi
if [ ! -f "ltmain.sh" ]; then
	cp auto/ltmain.sh .
fi
touch libtoolT
auto/config.status
rm -f libtoolT

#end
