#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withmost,v 1.6 2015/02/25 00:43:23 cvsuser Exp $
#       auto select the terminal interface (ncurses, tinfo, curse, termcap and termlib)
#       enable most other third-party library support
#

./configure_new \
	--with-8bit		\
	--with-icu		\
	--with-apriconv		\
	--with-iconv		\
	--with-enca		\
	--with-openssl		\
	--with-dlmalloc		\
	$*

#end

