#!/bin/sh
# -*- mode: sh; -*-
# $Id: configure_new,v 1.4 2012/03/08 22:53:32 cvsuser Exp $
#

if [ ! -f "install-sh" ]; then
	cp auto/install-sh .
fi
if [ ! -f "config.guess" ]; then
	cp auto/config.guess .
fi
if [ ! -f "config.sub" ]; then
	cp auto/config.sub .
fi
if [ ! -f "missing" ]; then
	cp auto/missing .
fi
if [ ! -f "ltmain.sh" ]; then
	cp auto/ltmain.sh .
fi
if [ -f "auto/config.cache" ]; then
	rm auto/config.cache
fi
CONFIG_STATUS=auto/config.status \
	auto/configure "$@" --srcdir="${srcdir:-.}" --cache-file=auto/config.cache

#end
