#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withncursesw,v 1.4 2019/05/05 23:51:36 cvsuser Exp $
#   Basic configuration enabled using ncursesw
#

./configure_new \
	--with-8bit \
	--with-mouse \
	--with-termlib=ncursesw \
	--with-dlmalloc \
	$*

