#!/bin/sh
# -*- mode: sh; -*-
# $Id: config_withncursesw,v 1.3 2014/10/25 17:37:21 ayoung Exp $
#   Basic configuration enabled using ncursesw
#

./configure_new \
	--with-8bit \
	--with-termlib=ncursesw \
	--with-dlmalloc \
	$*

