#!/bin/sh
# -*- mode: sh; -*-
# $Id: configure_build,v 1.6 2023/03/06 15:19:31 cvsuser Exp $
#

if [ ! -f "install-sh" ]; then
	cp auto/install-sh .
fi
if [ ! -f "config.guess" ]; then
	cp auto/config.guess .
fi
if [ ! -f "config.sub" ]; then
	cp auto/config.sub .
fi
if [ ! -f "missing" ]; then
	if [ -f "missing" ]; then
		cp auto/missing .
	fi
fi
if [ ! -f "ltmain.sh" ]; then
	cp auto/ltmain.sh .
fi
touch libtoolT
auto/config.status
rm -f libtoolT

#end
