// Auto-generated by Makefile
#define VERSION "1.13.4.gr"
#define BINM_APROPOS "grapropos"
#define BINM_MAKEWHATIS "grmakewhatis"
#define BINM_MAN "grman"
#define BINM_SOELIM "grsoelim"
#define BINM_WHATIS "grwhatis"
#define MAN_CONF_FILE "/etc/grman.conf"
#define MANPATH_DEFAULT "/usr/share/man:/usr/X11R6/man:/usr/local/man"
