/* $Id: sun3.cr,v 1.4 2014/10/22 02:34:30 ayoung Exp $
 * Keyboard labels for a Sun keyboard type3
 *
 *
 */

# include "../alt.h"

list kbd_labels =
{
F(1),           "<L1>",
F(2),           "<L2>",
F(3),           "<L3>",
F(4),           "<L4>",
F(5),           "<L5>",
F(6),           "<L6>",
F(7),           "<L7>",
F(8),           "<L8>",
F(9),           "<L9>",
F(10),          "<L10>",
CF(1),          "<Ctrl-L1>",
CF(2),          "<Ctrl-L2>",
CF(3),          "<Ctrl-L3>",
CF(4),          "<Ctrl-L4>",
CF(5),          "<Ctrl-L5>",
CF(6),          "<Ctrl-L6>",
CF(7),          "<Ctrl-L7>",
CF(8),          "<Ctrl-L8>",
CF(9),          "<Ctrl-L9>",
CF(10),         "<Ctrl-L10>",
CF(11),         "<Ctrl-L11>",
CF(12),         "<Ctrl-L12>",
AF(1),          "<LEFT-L1>",
AF(2),          "<LEFT-L2>",
AF(3),          "<LEFT-L3>",
AF(4),          "<LEFT-L4>",
AF(5),          "<LEFT-L5>",
AF(6),          "<LEFT-L6>",
AF(7),          "<LEFT-L7>",
AF(8),          "<LEFT-L8>",
AF(9),          "<LEFT-L9>",
AF(10),         "<LEFT-L10>",
AF(11),         "<LEFT-L11>",
AF(12),         "<LEFT-L12>",
ALT_A,                  "<LEFT-A>",
ALT_B,                  "<LEFT-B>",
ALT_C,                  "<LEFT-C>",
ALT_D,                  "<LEFT-D>",
ALT_E,                  "<LEFT-E>",
ALT_F,                  "<LEFT-F>",
ALT_G,                  "<LEFT-G>",
ALT_H,                  "<LEFT-H>",
ALT_I,                  "<LEFT-I>",
ALT_J,                  "<LEFT-J>",
ALT_K,                  "<LEFT-K>",
ALT_L,                  "<LEFT-L>",
ALT_M,                  "<LEFT-M>",
ALT_N,                  "<LEFT-N>",
ALT_O,                  "<LEFT-O>",
ALT_P,                  "<LEFT-P>",
ALT_Q,                  "<LEFT-Q>",
ALT_R,                  "<LEFT-R>",
ALT_S,                  "<LEFT-S>",
ALT_T,                  "<LEFT-T>",
ALT_U,                  "<LEFT-U>",
ALT_V,                  "<LEFT-V>",
ALT_W,                  "<LEFT-W>",
ALT_X,                  "<LEFT-X>",
ALT_Y,                  "<LEFT-Y>",
ALT_Z,                  "<LEFT-Z>",
MOD_META | '0',         "<LEFT-0>",
MOD_META | '1',         "<LEFT-1>",
MOD_META | '2',         "<LEFT-2>",
MOD_META | '3',         "<LEFT-3>",
MOD_META | '4',         "<LEFT-4>",
MOD_META | '5',         "<LEFT-5>",
MOD_META | '6',         "<LEFT-6>",
MOD_META | '7',         "<LEFT-7>",
MOD_META | '8',         "<LEFT-8>",
MOD_META | '9',         "<LEFT-9>",
};

