name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: x86
    - uses: shogo82148/actions-setup-perl@v1
      if: runner.os == 'XXWindows'
      with:
        perl-version: '5.30'
        distribution: strawberry
    - name: Windows, generating Makefiles
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        @set PERL=c:/Strawberry/perl/bin/perl
        c:/Strawberry/perl/bin/perl makelib.pl --perlpath=c:/Strawberry/perl/bin --busybox=./win32/busybox --wget=./win32/wget --bison=./bin/bison --flex=./bin/flex --verbose vc2019
        dir c:\tools
        dir c:\msys64
        dir c:\msys64\usr\bin
    - name: Windows, compiling
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        @REM set PERL=C:/hostedtoolcache/windows/strawberry-perl/5.30.3/x64/perl/bin/perl
        @set PERL=c:/Strawberry/perl/bin/perl
        .\win32\gmake-42 contrib
        .\win32\gmake-42
        exit 0
    - name: Windows, diagnose build errors
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: code-build-artifacts
        path: ./libchartable/charsetlocales.h
    - name: Linux, generating Makefiles
      if: runner.os == 'Linux'
      shell: bash
      run: |
        ./support/config_withncurses        
    - name: Linux, compiling
      if: runner.os == 'Linux'
      shell: bash
      run: |
        make        
