name: "Solaris build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test on Solaris 11.4
      uses: vmactions/solaris-vm@v1
      with:
        prepare: |
          pkg publisher solaris
          beadm list
          pkg list -a '*'
          pkg info entire
          pkg list -af entire
          pkg list -af gcc
          pkgutil -y -i gmake autoconf automake libtool
        mem: 6144
        run: |
          uname -a
          whoami
          pwd
          cat /etc/release
          PATH=/opt/csw/bin:$PATH
          export PATH
          ./configure --prefix=/usr
          gmake release build
