name: "Solaris build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test on Solaris 11.4
      uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        mem: 6144
        prepare: |
          export LC_ALL=C
          export LANG=C
          pkg publisher solaris
          beadm list
          pkg info entire
          pkg list -af entire
          echo ===== Installed packages 
          pkg list '*'
          echo ===== Available developer/library packages 
          pkg list -a 'developer/*'
          pkg list -a 'library/*'
          echo ===== Packages requirements
          pkg install -v system/locale system/header
          pkg install -v --accept \
            developer/gcc-11 \
            developer/build/gnu-make \
            developer/build/make \
            developer/build/autoconf \
            developer/build/autoconf \
            developer/build/libtool \
            developer/build/pkg-config \
            developer/lexer/flex \
            developer/parser/bison
          
        run: |
          export LC_ALL=C
          export LANG=C
          uname -a
          whoami
          pwd
          cat /etc/release
          PATH=/opt/csw/bin:$PATH:/usr/sfw/bin
          export PATH
          ./configure --prefix=/usr
          gmake release build  
