name: "Solaris build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test on Solaris 11.4
      uses: vmactions/solaris-vm@v1
      with:
        usesh: true
        mem: 6144
        prepare: |
          pkg publisher solaris
          beadm list
          pkg info entire
          pkg list -af entire
          pkg list -a 'developer/*'
          pkg list -a 'library/*'
          pkg install -v system/locale
          pkg install -v --accept developer/base-developer-utilities developer/gcc-11
          pkg install -v --accept developer/build/gnu-make developer/build/libtool developer/build/pkg-config
          pkg install -v --accept developer/lexer/flex developer/parser/bison
          pkg install -v --accept library/libarchive library/ncurses        
        run: |
          uname -a
          whoami
          pwd
          cat /etc/release
          PATH=/opt/csw/bin:$PATH
          export PATH
          ./configure --prefix=/usr
          gmake release build
          
