name: "Solaris build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test on Solaris 11.4
      uses: vmactions/solaris-vm@v1
      with:
        prepare: |
          pkg publisher solaris
          beadm list
          pkg info entire
          pkg list -af entire
          pkg list -af gcc-7
          pkg install -v --accept developer/gcc-7@7.3.0-11.4.0.0.1.14.0
          pkgutil -y -i bash gmake autoconf automake libtool pkgconf perl flex bison wget
          pkgutil -y -i libarchive libcurl libncurses
        mem: 6144
        run: |
          uname -a
          whoami
          pwd
          cat /etc/release
          PATH=/opt/csw/bin:$PATH
          export PATH
          ./configure --prefix=/usr
          gmake release build
